In [0]:
# KNU AI Lecture
import numpy as np

In [0]:
a = np.array((0,10,20,30))

In [0]:
b = np.array((0,1,2))

In [0]:
y = a[:,None] + b

In [47]:
print(y)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
